# Site settings
title: Weltreise von Ümit und Georg
header-img: img/home-bg.jpg
email: uemit.seren@gmail.com
description: "Ein umfassender Bericht über Ümit und Georg's 4 monatige Weltreise 2005/2006"
baseurl: "/around-the-world"
url: ""
github_username:  timeu
facebook_username:  timeu

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# Jekyll Redirect From Plugin for Redirects from Start Bootstrap Old Version
gems:
  - jekyll-paginate
